<?php
if (!defined('ABSPATH')) exit;

class WPMazic_Meta_Tags {

    /**
     * Plugin settings from wpmazic_settings option.
     *
     * @var array
     */
    private $settings = array();

    /**
     * Constructor — register all hooks.
     */
    public function __construct() {
        $this->settings = get_option('wpmazic_settings', array());

        // Remove the default WordPress canonical so we can handle it ourselves.
        remove_action('wp_head', 'rel_canonical');

        // Output our meta tags early in wp_head.
        add_action('wp_head', array($this, 'output_meta_tags'), 1);

        // Filter the <title> tag parts generated by wp_get_document_title().
        add_filter('document_title_parts', array($this, 'filter_title_parts'), 15);
        add_filter('document_title_separator', array($this, 'filter_title_separator'), 15);
    }

    // ------------------------------------------------------------------
    //  Helpers
    // ------------------------------------------------------------------

    /**
     * Return a setting value with an optional default.
     */
    private function get_setting($key, $default = '') {
        return isset($this->settings[$key]) ? $this->settings[$key] : $default;
    }

    /**
     * Site name — from settings or fallback to bloginfo.
     */
    private function get_site_name() {
        $name = $this->get_setting('site_name', '');
        return $name !== '' ? $name : get_bloginfo('name');
    }

    /**
     * Title separator — from settings or fallback.
     */
    private function get_separator() {
        $sep = $this->get_setting('separator', '-');
        return $sep !== '' ? $sep : '-';
    }

    /**
     * Whether Open Graph output is enabled.
     */
    private function is_og_enabled() {
        // Default to enabled (1) when the setting has never been saved.
        return (int) $this->get_setting('enable_og', 1) === 1;
    }

    /**
     * Clip text to a max length with ellipsis.
     */
    private function clip_text($text, $limit = 160) {
        $text = trim( preg_replace( '/\s+/', ' ', (string) $text ) );
        if ( '' === $text ) {
            return '';
        }

        if ( function_exists( 'mb_strlen' ) && function_exists( 'mb_substr' ) ) {
            if ( mb_strlen( $text ) > $limit ) {
                return mb_substr( (string) $text, 0, $limit - 3 ) . '...';
            }
            return $text;
        }

        if ( strlen( $text ) > $limit ) {
            return substr( (string) $text, 0, $limit - 3 ) . '...';
        }

        return $text;
    }

    /**
     * Build replacement context for singular template variables.
     */
    private function build_post_template_context($post_id) {
        $post = get_post( $post_id );
        if ( ! $post ) {
            return array();
        }

        $excerpt = $post->post_excerpt ? $post->post_excerpt : $post->post_content;
        $excerpt = wp_strip_all_tags( strip_shortcodes( (string) $excerpt ) );
        $excerpt = $this->clip_text( $excerpt, 160 );

        $keyword = get_post_meta( $post_id, '_wpmazic_keyword', true );
        $author  = get_the_author_meta( 'display_name', (int) $post->post_author );
        $date    = get_the_date( 'Y-m-d', $post_id );

        $category_label = '';
        $categories = get_the_terms( $post_id, 'category' );
        if ( is_array( $categories ) && ! empty( $categories[0] ) && isset( $categories[0]->name ) ) {
            $category_label = (string) $categories[0]->name;
        }

        return array(
            '%title%'           => get_the_title( $post_id ),
            '%sitename%'        => $this->get_site_name(),
            '%sep%'             => $this->get_separator(),
            '%excerpt%'         => $excerpt,
            '%primary_keyword%' => trim( (string) $keyword ),
            '%post_type%'       => (string) get_post_type( $post_id ),
            '%category%'        => $category_label,
            '%date%'            => (string) $date,
            '%author%'          => (string) $author,
        );
    }

    /**
     * Apply variable replacement for a configured template.
     */
    private function apply_template($template, $context) {
        $template = (string) $template;
        if ( '' === trim( (string) $template ) ) {
            return '';
        }

        $rendered = strtr( $template, $context );
        $rendered = preg_replace( '/%[a-z_]+%/i', '', (string) $rendered );
        $rendered = trim( preg_replace( '/\s+/', ' ', (string) $rendered ) );
        return $rendered;
    }

    /**
     * Build the SEO title for the current page.
     */
    private function get_seo_title() {
        $sep       = $this->get_separator();
        $site_name = $this->get_site_name();

        if (is_singular()) {
            $post_id = get_the_ID();
            $title   = get_post_meta($post_id, '_wpmazic_title', true);
            if (empty($title)) {
                $template = $this->get_setting( 'title_template_singular', '%title% %sep% %sitename%' );
                $context  = $this->build_post_template_context( $post_id );
                $title    = $this->apply_template( $template, $context );
                if ( empty( $title ) ) {
                    $title = get_the_title($post_id) . ' ' . $sep . ' ' . $site_name;
                }
                return $title;
            }
            return $title . ' ' . $sep . ' ' . $site_name;
        }

        if (is_front_page() || is_home()) {
            $tagline = get_bloginfo('description');
            return $tagline ? $site_name . ' ' . $sep . ' ' . $tagline : $site_name;
        }

        if (is_category() || is_tag() || is_tax()) {
            return single_term_title('', false) . ' ' . $sep . ' ' . $site_name;
        }

        if (is_post_type_archive()) {
            return post_type_archive_title('', false) . ' ' . $sep . ' ' . $site_name;
        }

        if (is_author()) {
            return get_the_author() . ' ' . $sep . ' ' . $site_name;
        }

        if (is_date()) {
            if (is_year()) {
                $label = get_the_date('Y');
            } elseif (is_month()) {
                $label = get_the_date('F Y');
            } else {
                $label = get_the_date();
            }
            return $label . ' ' . $sep . ' ' . $site_name;
        }

        if (is_search()) {
            /* translators: %s: search query */
            return sprintf(__('Search Results for &#8220;%s&#8221;', 'wpmazic-seo-lite'), get_search_query()) . ' ' . $sep . ' ' . $site_name;
        }

        if (is_404()) {
            return __('Page Not Found', 'wpmazic-seo-lite') . ' ' . $sep . ' ' . $site_name;
        }

        return $site_name;
    }

    /**
     * Build the meta description for the current page.
     */
    private function get_seo_description() {
        if (is_singular()) {
            $post_id = get_the_ID();
            $desc    = get_post_meta($post_id, '_wpmazic_description', true);
            if (!empty($desc)) {
                return $desc;
            }
            $template = $this->get_setting( 'description_template_singular', '%excerpt%' );
            $context  = $this->build_post_template_context( $post_id );
            $desc     = $this->apply_template( $template, $context );
            if ( ! empty( $desc ) ) {
                return $this->clip_text( $desc, 160 );
            }

            // Auto-generate from excerpt / content.
            $post = get_post($post_id);
            if ($post) {
                $text = $post->post_excerpt ? $post->post_excerpt : $post->post_content;
                $text = wp_strip_all_tags(strip_shortcodes($text));
                return $this->clip_text( $text, 160 );
            }
        }

        if (is_category() || is_tag() || is_tax()) {
            $desc = term_description();
            if (!empty($desc)) {
                $desc = wp_strip_all_tags($desc);
                if (mb_strlen($desc) > 160) {
                    $desc = mb_substr( (string) $desc, 0, 157) . '...';
                }
                return $desc;
            }
        }

        if (is_author()) {
            $desc = get_the_author_meta('description');
            if (!empty($desc)) {
                if (mb_strlen($desc) > 160) {
                    $desc = mb_substr( (string) $desc, 0, 157) . '...';
                }
                return $desc;
            }
        }

        if (is_front_page() || is_home()) {
            return get_bloginfo('description');
        }

        return '';
    }

    /**
     * Return the canonical URL for the current page.
     */
    private function get_canonical_url() {
        if (is_singular()) {
            $post_id   = get_the_ID();
            $canonical = get_post_meta($post_id, '_wpmazic_canonical', true);
            if (!empty($canonical)) {
                return $canonical;
            }
            return get_permalink($post_id);
        }

        if (is_front_page() || is_home()) {
            return home_url('/');
        }

        if (is_category() || is_tag() || is_tax()) {
            $term = get_queried_object();
            if ($term && !is_wp_error($term)) {
                return get_term_link($term);
            }
        }

        if (is_post_type_archive()) {
            return get_post_type_archive_link(get_queried_object()->name);
        }

        if (is_author()) {
            return get_author_posts_url(get_queried_object_id());
        }

        if (is_date()) {
            if (is_year()) {
                return get_year_link(get_query_var('year'));
            }
            if (is_month()) {
                return get_month_link(get_query_var('year'), get_query_var('monthnum'));
            }
            return get_day_link(get_query_var('year'), get_query_var('monthnum'), get_query_var('day'));
        }

        if (is_search()) {
            return get_search_link();
        }

        return '';
    }

    /**
     * Get the primary image URL for the current page (used for OG / Twitter).
     */
    private function get_page_image() {
        if (is_singular()) {
            $post_id = get_the_ID();
            if (has_post_thumbnail($post_id)) {
                return get_the_post_thumbnail_url($post_id, 'large');
            }
        }
        return '';
    }

    /**
     * Determine OG type.
     */
    private function get_og_type() {
        if (is_singular('post')) {
            return 'article';
        }
        if (is_author()) {
            return 'profile';
        }
        return 'website';
    }

    // ------------------------------------------------------------------
    //  Robots
    // ------------------------------------------------------------------

    /**
     * Build the robots meta content (noindex, nofollow) for the current page.
     *
     * Returns an empty string when default indexing/following should apply.
     */
    private function get_robots_meta() {
        $directives = array();

        // Per-post overrides.
        if (is_singular()) {
            $post_id = get_the_ID();
            if (get_post_meta($post_id, '_wpmazic_noindex', true)) {
                $directives[] = 'noindex';
            }
            if (get_post_meta($post_id, '_wpmazic_nofollow', true)) {
                $directives[] = 'nofollow';
            }
            if (get_post_meta($post_id, '_wpmazic_noarchive', true)) {
                $directives[] = 'noarchive';
            }
            if (get_post_meta($post_id, '_wpmazic_nosnippet', true)) {
                $directives[] = 'nosnippet';
            }
            if (get_post_meta($post_id, '_wpmazic_noimageindex', true)) {
                $directives[] = 'noimageindex';
            }
        }

        // Global archive settings.
        if (is_category() && $this->get_setting('noindex_categories')) {
            $directives[] = 'noindex';
        }
        if (is_tag() && $this->get_setting('noindex_tags')) {
            $directives[] = 'noindex';
        }
        if ((is_date() || is_author()) && $this->get_setting('noindex_archives')) {
            $directives[] = 'noindex';
        }
        if ( is_attachment() && $this->get_setting( 'noindex_attachments' ) ) {
            $directives[] = 'noindex';
        }

        // Search and 404 should never be indexed.
        if (is_search() || is_404()) {
            $directives[] = 'noindex';
        }

        $has_noindex = in_array( 'noindex', $directives, true );
        $has_nosnippet = in_array( 'nosnippet', $directives, true );
        $has_noimageindex = in_array( 'noimageindex', $directives, true );

        // Advanced robots controls for SERP snippet/media behavior.
        if ( ! $has_noindex ) {
            $max_snippet = $this->get_setting( 'robots_max_snippet', -1 );
            if ( ! $has_nosnippet && is_numeric( $max_snippet ) ) {
                $directives[] = 'max-snippet:' . intval( $max_snippet );
            }

            $max_video = $this->get_setting( 'robots_max_video_preview', -1 );
            if ( is_numeric( $max_video ) ) {
                $directives[] = 'max-video-preview:' . intval( $max_video );
            }

            $max_image = strtolower( trim( (string) $this->get_setting( 'robots_max_image_preview', 'large' ) ) );
            if ( ! $has_noimageindex && in_array( $max_image, array( 'none', 'standard', 'large' ), true ) ) {
                $directives[] = 'max-image-preview:' . $max_image;
            }
        }

        // Optional free-form directives from settings (comma or newline separated).
        $custom = trim( (string) $this->get_setting( 'robots_meta', '' ) );
        if ( '' !== $custom ) {
            $parts = preg_split( '/[\r\n,]+/', $custom );
            if ( is_array( $parts ) ) {
                foreach ( $parts as $part ) {
                    $part = strtolower( trim( preg_replace( '/[^a-z0-9\-\:_]/i', '', (string) $part ) ) );
                    if ( '' !== $part ) {
                        $directives[] = $part;
                    }
                }
            }
        }

        $directives = array_unique($directives);
        return implode(', ', $directives);
    }

    /**
     * Build legacy keywords meta value from the primary focus keyword.
     *
     * @return string
     */
    private function get_keywords_meta() {
        if ( ! is_singular() ) {
            return '';
        }

        $post_id = get_the_ID();
        $primary = get_post_meta( $post_id, '_wpmazic_keyword', true );
        return ! empty( $primary ) ? sanitize_text_field( $primary ) : '';
    }

    // ------------------------------------------------------------------
    //  Title tag integration
    // ------------------------------------------------------------------

    /**
     * Filter document_title_parts so the <title> tag matches our SEO title.
     *
     * @param  array $title_parts
     * @return array
     */
    public function filter_title_parts($title_parts) {
        if (is_singular()) {
            $post_id = get_the_ID();
            $custom  = get_post_meta($post_id, '_wpmazic_title', true);
            if (!empty($custom)) {
                $title_parts['title'] = $custom;
            }
        }

        $title_parts['site'] = $this->get_site_name();

        return $title_parts;
    }

    /**
     * Filter the title separator.
     *
     * @param  string $sep
     * @return string
     */
    public function filter_title_separator($sep) {
        return $this->get_separator();
    }

    // ------------------------------------------------------------------
    //  Output
    // ------------------------------------------------------------------

    /**
     * Main output method hooked to wp_head.
     */
    public function output_meta_tags() {
        // Don't output anything inside the admin or during AJAX / REST requests.
        if (is_admin() || wp_doing_ajax()) {
            return;
        }

        $title       = $this->get_seo_title();
        $description = $this->get_seo_description();
        $canonical   = $this->get_canonical_url();
        $robots      = $this->get_robots_meta();
        $keywords    = $this->get_keywords_meta();
        $image       = $this->get_page_image();
        $og_type     = $this->get_og_type();

        // --- Standard meta tags ------------------------------------------

        if (!empty($title)) {
            echo '<meta name="title" content="' . esc_attr($title) . '">' . "\n";
        }

        if (!empty($description)) {
            echo '<meta name="description" content="' . esc_attr($description) . '">' . "\n";
        }

        if (!empty($robots)) {
            echo '<meta name="robots" content="' . esc_attr($robots) . '">' . "\n";
        }

        if (!empty($keywords)) {
            echo '<meta name="keywords" content="' . esc_attr($keywords) . '">' . "\n";
        }

        // --- Canonical ---------------------------------------------------

        if (!empty($canonical)) {
            echo '<link rel="canonical" href="' . esc_url($canonical) . '">' . "\n";
        }

        // --- Open Graph --------------------------------------------------

        if ($this->is_og_enabled()) {
            $this->output_og_tags($title, $description, $canonical, $image, $og_type);
        }

        // --- Twitter Cards -----------------------------------------------

        if ($this->is_og_enabled()) {
            $this->output_twitter_tags($title, $description, $image);
        }
    }

    /**
     * Output Open Graph meta tags.
     */
    private function output_og_tags($title, $description, $url, $image, $og_type) {
        $og_title       = $title;
        $og_description = $description;
        $og_image       = $image;

        // Per-post OG overrides.
        if (is_singular()) {
            $post_id = get_the_ID();

            $override_title = get_post_meta($post_id, '_wpmazic_og_title', true);
            if (!empty($override_title)) {
                $og_title = $override_title;
            }

            $override_desc = get_post_meta($post_id, '_wpmazic_og_description', true);
            if (!empty($override_desc)) {
                $og_description = $override_desc;
            }

            $override_img = get_post_meta($post_id, '_wpmazic_og_image', true);
            if (!empty($override_img)) {
                $og_image = $override_img;
            }

            if ( empty( $og_image ) ) {
                $dynamic = $this->get_dynamic_og_image_url( $post_id );
                if ( ! empty( $dynamic ) ) {
                    $og_image = $dynamic;
                }
            }
        }

        echo '<meta property="og:locale" content="' . esc_attr(get_locale()) . '">' . "\n";
        echo '<meta property="og:type" content="' . esc_attr($og_type) . '">' . "\n";

        if (!empty($og_title)) {
            echo '<meta property="og:title" content="' . esc_attr($og_title) . '">' . "\n";
        }

        if (!empty($og_description)) {
            echo '<meta property="og:description" content="' . esc_attr($og_description) . '">' . "\n";
        }

        if (!empty($url)) {
            echo '<meta property="og:url" content="' . esc_url($url) . '">' . "\n";
        }

        echo '<meta property="og:site_name" content="' . esc_attr($this->get_site_name()) . '">' . "\n";

        if (!empty($og_image)) {
            echo '<meta property="og:image" content="' . esc_url($og_image) . '">' . "\n";
        }

        // Article-specific tags.
        if (is_singular('post')) {
            $post = get_post();
            if ($post) {
                echo '<meta property="article:published_time" content="' . esc_attr(mysql2date('c', $post->post_date_gmt, false)) . '">' . "\n";
                echo '<meta property="article:modified_time" content="' . esc_attr(mysql2date('c', $post->post_modified_gmt, false)) . '">' . "\n";
            }
        }
    }

    /**
     * Output Twitter Card meta tags.
     */
    private function output_twitter_tags($title, $description, $image) {
        $tw_title       = $title;
        $tw_description = $description;
        $tw_image       = $image;
        $tw_card        = !empty($image) ? 'summary_large_image' : 'summary';

        // Per-post Twitter overrides.
        if (is_singular()) {
            $post_id = get_the_ID();

            $override_title = get_post_meta($post_id, '_wpmazic_twitter_title', true);
            if (!empty($override_title)) {
                $tw_title = $override_title;
            }

            $override_desc = get_post_meta($post_id, '_wpmazic_twitter_description', true);
            if (!empty($override_desc)) {
                $tw_description = $override_desc;
            }

            $override_img = get_post_meta($post_id, '_wpmazic_twitter_image', true);
            if (!empty($override_img)) {
                $tw_image = $override_img;
                $tw_card  = 'summary_large_image';
            }

            if ( empty( $tw_image ) ) {
                $dynamic = $this->get_dynamic_og_image_url( $post_id );
                if ( ! empty( $dynamic ) ) {
                    $tw_image = $dynamic;
                    $tw_card  = 'summary_large_image';
                }
            }

            $override_card = get_post_meta($post_id, '_wpmazic_twitter_card', true);
            if (!empty($override_card)) {
                $tw_card = $override_card;
            }
        }

        echo '<meta name="twitter:card" content="' . esc_attr($tw_card) . '">' . "\n";

        if (!empty($tw_title)) {
            echo '<meta name="twitter:title" content="' . esc_attr($tw_title) . '">' . "\n";
        }

        if (!empty($tw_description)) {
            echo '<meta name="twitter:description" content="' . esc_attr($tw_description) . '">' . "\n";
        }

        if (!empty($tw_image)) {
            echo '<meta name="twitter:image" content="' . esc_url($tw_image) . '">' . "\n";
        }

        // twitter:site — use site_name as a sensible fallback.
        $twitter_site = trim( (string) $this->get_setting( 'twitter_site', '' ) );
        if ( '' !== $twitter_site ) {
            // Ensure it starts with @.
            if ( 0 !== strpos( (string) $twitter_site, '@' ) ) {
                $twitter_site = '@' . $twitter_site;
            }
            echo '<meta name="twitter:site" content="' . esc_attr( $twitter_site ) . '">' . "\n";
        }
    }

    /**
     * Get dynamic OG image URL when feature is enabled.
     *
     * @param int $post_id Post ID.
     * @return string
     */
    private function get_dynamic_og_image_url( $post_id ) {
        $enabled = (int) $this->get_setting( 'enable_dynamic_og_image', 1 ) === 1;
        if ( ! $enabled || ! is_singular() ) {
            return '';
        }

        $post_id = absint( $post_id );
        if ( $post_id <= 0 ) {
            return '';
        }

        if ( class_exists( 'WPMazic_Dynamic_OG' ) ) {
            return WPMazic_Dynamic_OG::get_image_url( $post_id );
        }

        return home_url( '/wpmazic-og/' . $post_id . '.svg' );
    }
}
